sonar.organization=starkora
sonar.projectKey=Starkora_PharmaSys
sonar.projectName=PharmaSys
sonar.projectVersion=1.0.0

sonar.host.url=https://sonarcloud.io

# Módulos del proyecto
sonar.modules=backend,frontend

# ── Backend (Java/Spring Boot) ──────────────────────────────
backend.sonar.projectName=PharmaSys Backend
backend.sonar.projectBaseDir=backend
backend.sonar.sources=src/main/java
backend.sonar.tests=src/test/java
backend.sonar.java.binaries=target/classes
backend.sonar.java.test.binaries=target/test-classes
backend.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
backend.sonar.exclusions=**/config/**,**/model/**,**/*Application.java

# ── Frontend (Angular/TypeScript) ───────────────────────────
frontend.sonar.projectName=PharmaSys Frontend
frontend.sonar.projectBaseDir=frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/environments/**
frontend.sonar.tests=src
frontend.sonar.test.inclusions=**/*.spec.ts
frontend.sonar.javascript.lcov.reportPaths=coverage/pharmasys-frontend/lcov.info

# ── Exclusiones globales ─────────────────────────────────────
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/*.min.js,database/**
